language: node_js
node_js:
- '7'
before_install:
- npm install -g npm@'^5.10.0'
- npm install -g NeApp/neon-extension-build#$TRAVIS_BRANCH || npm install -g NeApp/neon-extension-build#develop
install:
- neb travis:install $TRAVIS_BRANCH
- neb package:validate
- git diff --exit-code
script:
- npm run test
- npm run lint
- if [ ! -f ./Build/Coverage/lcov.info ]; then exit 1; fi
after_success:
- npm install -g coveralls
- cat ./Build/Coverage/lcov.info | coveralls
deploy:
  provider: npm
  email: neapp-ci@me.dgardiner.net
  api_key:
    secure: N7ApgroyfXX1vMUgsqM38dZW3gHuyvqYm4J3rSjCbh3QBJ9HjeCe47/1n5Cqd7Kf5z+9wNS/efSd/WADpMTceoWryEC7oGNn0KnzGnO3YELsTunY72iN7JEIKxcbvaxj5HTGpEUR6f4atSzIyw8Pcdufod16H3bKfAVaO8+A3mZi3N3O/YoUPwC8ZRcIR+2RgYQk30hnmD+xlA2ikpKFMEKDOzASRkhOzl0VwIomquyJ6mAUcQdFG8EkqdqNBAPpRKRfr8lshME06IYvuehggeMwWFlFSTHchr3sSY1RGDqNI3DXd5I/lC1hiy/ZbDeA7tWRM7sTa6lQ7Tk8rlnkjULhJKluPqilrlp6dB68Uqob8VzjcyXMY6iruks1ZzBXYhRhxdX+KGwJ1GZUoXVkT31yacWjKIhQYrt1HYXiENuR6y5hwP612LkKPUKPC7aPWTScpw5rIFxvrsrTSTHzJ9GDUFvfsNR9EJMagRjnYSpUkwTntLGDGxiiKS4PY1NgyAwqH5txvk7wwgu9b1FeIT0GKbyxs+5XtVTe6+6VpdpA7wjvf/zic84radWDNhLkNlw+cuUzQIlOtJp7/YH5E9mt73+O5rlKwyRQQ1yt63G6M8AqlF1K+x6MyiblmaopMXUg9bKcnwYLjcAE76cdNk56UTX+kHNow0nCVdkhi4Q=
  on:
    repo: NeApp/neon-extension-source-netflix
    tags: true
