language: node_js
node_js:
- '7'
before_install:
- npm install -g npm@'^5.10.0'
- npm install -g RadonApp/radon-extension-build#$TRAVIS_BRANCH || npm install -g RadonApp/radon-extension-build#develop
install:
- neb travis:install $TRAVIS_BRANCH
- neb package:validate
- git diff --exit-code
script:
- npm run test
- npm run lint
- if [ ! -f ./Build/Coverage/lcov.info ]; then exit 1; fi
after_success:
- npm install -g coveralls
- cat ./Build/Coverage/lcov.info | coveralls
deploy:
  provider: npm
  email: ci@radon.app
  api_key:
    secure: daHS34E0Rd9hwkvOuaXrhGopAXZMfu8VGsSe+YKmjCRMFlEdSJF7CGIuE7LxMp5t8B9guRs9YWMGAFGuPPYaA7TFQnnKcszbbYy+pHw3d7gfW1wydfHC1zdWaI/zpH1wuhUuLuNvGWPX5dLKXcnN3SVX9TGE07wVd6jw2Js6l4AEw1mHV0XTitw9/8oogu4Zw8fuqdw4/LozMad7YtWoePnL5yFOfcxgwMdHxNaAC626BbuFClsNavI0r9+92lesJ/wedxBt/KXnpOIqCjH31BRQ6uqFxgUIo+b2gv/SPtm9tUIXhrKIY953eKLvrzocjqsjsABJLadyYk4RJC8max2AxVoGPc/NC42f1onGZ/G8RrWXPM9CYapOeWal297GNkz0LY2ltFyyIMBwjkcjJ28PNzXH0uZqv9GeKG1ulkidV/h+rKni5zk29L16SapQAdxu/IctF17gZHTM+kabaiCTuYz2EALQkCvcriwcc7PwGjpvBkvhZaPDgnZ4J0Hym9aPbYEv9Go3+dT0s1F/RnvJGEGvgooA56bBkm/a5CaA2LLGVD2QN40ARYglZ/00itWlwCOkjmUP5hF1+oUsRaPkbZAql4kMniYZ0WTQ2JvQm8L8U+XEy0KnXJbDZ8i9A/SMB0EPhiKl6azppNmhQx3mzYTkGJAuHdZiJ/otG/Y=
  on:
    tags: true
    repo: RadonApp/radon-extension-plugin-netflix
